services:
    pa_contenttools.configuration:
        class: Pragmagency\ContentTools\Configuration\ContenttoolsConfiguration
        calls:
            -   method: setRepositoryLocator
                arguments:
                    - '@pa_contenttools.repository_locator'
            -   method: setSecurityCheckerLocator
                arguments:
                    - '@pa_contenttools.security_checker_locator'

    Pragmagency\ContentTools\Configuration\ContenttoolsConfigurationInterface:
        alias: pa_contenttools.configuration
