services:
    pa_contenttools.configuration:
        class: Pragmagency\ContentTools\Configuration\ContenttoolsConfiguration
        calls:
            -   method: setRetrieverLocator
                arguments:
                    - '@pa_contenttools.retriever_locator'
            -   method: setPersisterLocator
                arguments:
                    - '@pa_contenttools.persister_locator'
            -   method: setSecurityCheckerLocator
                arguments:
                    - '@pa_contenttools.security_checker_locator'

    Pragmagency\ContentTools\Configuration\ContenttoolsConfigurationInterface:
        alias: pa_contenttools.configuration
