services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pragmagency\ContentTools\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
