services:
    _defaults:
        autowire: true
        autoconfigure: true

    pa_contenttools.persister_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                file: '@Pragmagency\ContentTools\Persister\InFilePersister'

    Pragmagency\ContentTools\Persister\:
        resource: '../../Persister'
