services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rootDir: '%kernel.project_dir%'

    pa_contenttools.repository_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                file: '@Pragmagency\ContentTools\Repository\InFileRepository'

    Pragmagency\ContentTools\Repository\:
        resource: '../../Repository'
