services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rootDir: '%kernel.project_dir%'

    pa_contenttools.retriever_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                file: '@Pragmagency\ContentTools\Retriever\InFileRetriever'

    Pragmagency\ContentTools\Retriever\:
        resource: '../../Retriever'
